# Generated by Django 5.2.4 on 2025-08-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_customuser_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_pics/'),
        ),
    ]
